Run all configs

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -28,9 +28,9 @@ concurrency:
 jobs:
   matrix_prep:
     runs-on: ubuntu-latest
+    if: github.repository == 'open-cmsis-pack/cmsis-toolbox'
     outputs:
-      build_matrix: ${{ steps.build_matrix.outputs.matrix }}
-      test_matrix: ${{ steps.test_matrix.outputs.matrix }}
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
     steps:
       - name: Harden Runner
         uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
@@ -39,23 +39,17 @@ jobs:
 
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
       - uses: JoshuaTheMiller/conditional-build-matrix@81b51eb8d89e07b86404934b5fecde1cea1163a5 # v2.0.1
-        id: build_matrix
+        id: set-matrix
         with:
           inputFile: '.github/matrix_includes.json'
           filter: '[?runOnBranch==`always`]'
-
-      - uses: JoshuaTheMiller/conditional-build-matrix@81b51eb8d89e07b86404934b5fecde1cea1163a5 # v2.0.1
-        id: test_matrix
-        with:
-          inputFile: '.github/matrix_includes.json'
-          filter: '[?runOnBranch==`always` && runTest==`true`]'
 
   create-toolbox:
     needs: [ matrix_prep ]
     runs-on: ${{ matrix.runs_on }}
     continue-on-error: true
     strategy:
-      matrix: ${{ fromJson(needs.matrix_prep.outputs.build_matrix) }}
+      matrix: ${{ fromJson(needs.matrix_prep.outputs.matrix) }}
     steps:
       - name: Harden Runner
         uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
@@ -347,11 +341,12 @@ jobs:
           retention-days: ${{ env.retention-days }}
 
   run-tests:
+    name: Run Tests [${{ matrix.target }}-${{ matrix.arch }}]
     needs: [ matrix_prep, create-toolbox ]
     runs-on: ${{ matrix.runs_on }}
     continue-on-error: true
     strategy:
-      matrix: ${{ fromJson(needs.matrix_prep.outputs.test_matrix) }}
+      matrix: ${{ fromJson(needs.matrix_prep.outputs.matrix) }}
 
     steps:
       - name: Harden Runner
@@ -402,36 +397,8 @@ jobs:
         run: |
           echo "path=$(echo "$(pwd)/cmsis-toolbox/bin")" >> $GITHUB_OUTPUT
 
-      - name: Binary version linux-arm64
-        if: ${{ startsWith(matrix.runs_on, 'ubuntu') && matrix.arch == 'arm64' }}
-        uses: uraimo/run-on-arch-action@v2
-        with:
-          arch: aarch64
-          distro: ubuntu22.04
-          run: |
-            # Re-expose the toolbox directory and make sure it is executable
-            chmod -R +x ./cmsis-toolbox/bin/*
-            export PATH="$(pwd)/cmsis-toolbox/bin:$PATH"
-
-            echo "CMSIS-Toolbox binary versions (arm64):"
-            csolution    -V
-            cpackget     -V
-            cbuild       -V
-            cbuild2cmake -V
-            cbuildgen    -V
-
-      - name: Binary version info
-        if: ${{ matrix.arch != 'arm64' }}
-        shell: bash
-        run: |
-          export PATH="${{steps.toolbox_path.outputs.path}}:$PATH"
-          csolution -V
-          cpackget -V
-          cbuild -V
-          cbuild2cmake -V
-          cbuildgen -V
-
       - name: Run Test
+        id: run_robot
         shell: bash
         continue-on-error: true
         working-directory: ./test
@@ -444,6 +411,7 @@ jobs:
             --consolewidth=150 --settag ${{ matrix.target }}-${{ matrix.arch }} \
             --name ${{ matrix.target }}-${{ matrix.arch }} \
             ./e2e
+          echo "exit_code=$?" >> $GITHUB_OUTPUT
 
       - name: Archieve test results
         if: always()
@@ -452,6 +420,12 @@ jobs:
           name: reports-${{ matrix.target }}-${{ matrix.arch }}
           path: ./test/reports-${{ matrix.target }}-${{ matrix.arch }}
           retention-days: ${{ env.retention-days }}
+
+      - name: Fail job if Robot tests failed
+        if: steps.run_robot.outputs.exit_code != '0'
+        run: |
+          echo "Robot tests failed"
+          exit 1
 
   consolidate-report:
     if: always()
@@ -491,7 +465,10 @@ jobs:
         python -m robot.rebot --name Collective_Robot_Results --outputdir collective_robot_results --output output.xml \
           ./reports-windows-amd64/output.xml \
           ./reports-linux-amd64/output.xml \
-          ./reports-linux-arm64/output.xml
+          ./reports-darwin-amd64/output.xml \
+          ./reports-linux-arm64/output.xml \
+          ./reports-windows-arm64/output.xml \
+          ./reports-darwin-arm64/output.xml
 
     - name: Generate Summary report
       if: always()
